steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/github.com/faragos/lakesidemutual/customer-management-frontend:${COMMIT_SHA}', './customer-management-frontend']
images: ['gcr.io/${PROJECT_ID}/github.com/faragos/lakesidemutual/customer-management-frontend:${COMMIT_SHA}']
timeout: 1200s
