steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/github.com/faragos/lakesidemutual/customer-core:${COMMIT_SHA}', './customer-management-backend']
  env:
  - "DOCKER_BUILDKIT=1"
images: ['gcr.io/${PROJECT_ID}/github.com/faragos/lakesidemutual/customer-management-backend:${COMMIT_SHA}']
timeout: 12000s
