steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/github.com/faragos/lakesidemutual/customer-core:${COMMIT_SHA}', './customer-core']
  timeout: 1200s
images: ['gcr.io/${PROJECT_ID}/github.com/faragos/lakesidemutual/customer-core:${COMMIT_SHA}']
